version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend-web
    expose:
      - "8000"  # expose để Nginx truy cập, không public
    volumes:
      - ./backend/staticfiles:/static
      - ./backend/media:/app/media
    env_file:
      - .env
    command: ["gunicorn", "server.wsgi:application", "--bind", "0.0.0.0:8000"]
    networks:
      - webnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: typescript-frontend-web
    expose:
      - "80"  # chạy serve -l 80, expose cho Nginx dùng
    command: ["serve", "-s", "dist", "-l", "80"]
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
