version: '3.8'

services:
  backend:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./frontend/dist:/app/frontend/dist
    env_file:
      - .env
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: typescript-frontend
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
    stdin_open: true
    command: ["npm", "run", "dev"]

