# Generated by Django 4.2.20 on 2025-06-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0005_novelchapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangachapterimage',
            name='image',
            field=models.URLField(default='', max_length=500),
        ),
    ]
