# Generated by Django 4.2.20 on 2025-06-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0006_alter_mangachapterimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangachapterimage',
            name='image',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
