# Generated by Django 4.2.20 on 2025-06-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_alter_manga_numchapters_alter_manga_numcomments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='averageRating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='manga',
            name='numRatings',
            field=models.IntegerField(default=0),
        ),
    ]
