# Generated by Django 4.2.20 on 2025-06-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_manga_averagerating_manga_numratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='cover_image',
            field=models.ImageField(blank=True, default='manga_covers/default.jpg', max_length=500, upload_to='manga_covers/'),
        ),
    ]
