# Generated by Django 4.2.20 on 2025-06-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_comments_chapter_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='Tiểu sử của bạn ở đây', null=True),
        ),
    ]
