# Generated by Django 4.2.20 on 2025-06-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0009_customuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='post_id',
        ),
        migrations.AddField(
            model_name='favorite',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_post_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
