# Generated by Django 4.2.20 on 2025-06-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_favorite_post_id_favorite_content_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user', 'post_id')},
        ),
    ]
