# Generated by Django 4.2.20 on 2025-06-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_alter_novel_numchapters_alter_novel_numcomments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='averageRating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='novel',
            name='numRatings',
            field=models.IntegerField(default=0),
        ),
    ]
